{
 "title": "css-playground-tesla",
 "time": { "from": "2024-06-21T18:58:19.509Z", "to": "2024-06-21T19:09:38.263Z" },
 "templating": {
  "list": [
   { "name": "devices", "query": "3F78A21D" },
   {
    "name": "parameters",
    "query": "APP_environmentRainy,\nAPP_environmentSnowy,\nBMS_acChargerKwhTotal,\nBMS_activeHeatingWorthwhile,\nBMS_appCrc,\nBMS_appGitHash,\nBMS_assemblyId,\nBMS_battTempPct,\nBMS_bootCrc,\nBMS_bootGitHash,\nBMS_bootUdsProtoVersion,\nBMS_buildConfigId,\nBMS_buildType,\nBMS_chargeRequest,\nBMS_chargeRetryCount,\nBMS_chgPowerAvailable,\nBMS_componentId,\nBMS_contactorState,\nBMS_cpMiaOnHvs,\nBMS_dcChargerKwhTotal,\nBMS_diLimpRequest,\nBMS_ecuLogUploadRequest,\nBMS_energyBuffer,\nBMS_energyToChargeComplete,\nBMS_ensShouldBeActiveForDrive,\nBMS_expectedEnergyRemaining,\nBMS_fcContactorRequest,\nBMS_fcLinkOkToEnergizeRequest,\nBMS_fullChargeComplete,\nBMS_gpoHasCompleted,\nBMS_hardwareId,\nBMS_hvState,\nBMS_hvacPowerBudget,\nBMS_hvacPowerRequest,\nBMS_idealEnergyRemaining,\nBMS_internalHvilSenseV,\nBMS_isolationResistance,\nBMS_keepWarmRequest,\nBMS_kwhAcChargeTotalModule1,\nBMS_kwhAcChargeTotalModule2,\nBMS_kwhAcChargeTotalModule3,\nBMS_kwhAcChargeTotalModule4,\nBMS_kwhChargeTotalModule1,\nBMS_kwhChargeTotalModule2,\nBMS_kwhChargeTotalModule3,\nBMS_kwhChargeTotalModule4,\nBMS_kwhDcChargeTotalModule1,\nBMS_kwhDcChargeTotalModule2,\nBMS_kwhDcChargeTotalModule3,\nBMS_kwhDcChargeTotalModule4,\nBMS_kwhDischargeTotalModule1,\nBMS_kwhDischargeTotalModule2,\nBMS_kwhDischargeTotalModule3,\nBMS_kwhDischargeTotalModule4,\nBMS_kwhDriveDischargeTotal,\nBMS_kwhRegenChargeTotal,\nBMS_maxDischargePower,\nBMS_maxRegenPower,\nBMS_maxStationaryHeatPower,\nBMS_moduleType,\nBMS_nominalEnergyRemaining,\nBMS_nominalFullPackEnergy,\nBMS_notEnoughPowerForDrive,\nBMS_notEnoughPowerForHeatPump,\nBMS_notEnoughPowerForSupport,\nBMS_okToShipByAir,\nBMS_okToShipByLand,\nBMS_packContactorRequest,\nBMS_packMass,\nBMS_pcbaId,\nBMS_pcsPwmDisable,\nBMS_pcsPwmEnabled,\nBMS_platformMaxBusVoltage,\nBMS_platformType,\nBMS_powerLimitsState,\nBMS_preconditionAllowed,\nBMS_reservedConfig_0,\nBMS_smStateRequest,\nBMS_state,\nBMS_subUsageId,\nBMS_uiChargeStatus,\nBMS_updateAllowed,\nBMS_usageId,\nBMSdissipation312,\nBMSflowRequest312,\nBMSinletActiveCoolTarget312,\nBMSinletActiveHeatTarget312,\nBMSinletPassiveTarget312,\nBMSmaxPackTemperature,\nBMSminPackTemperature,\nBMSnoFlowRequest312,\nBMSpcsNoFlowRequest312,\nBattBeginningOfLifeEnergy292,\nBattBrickModelTMax332,\nBattBrickModelTMin332,\nBattBrickTempMax332,\nBattBrickTempMin332,\nBattBrickTempMinNum332,\nBattBrickVoltageMax332,\nBattBrickVoltageMaxNum332,\nBattBrickVoltageMin332,\nBattBrickVoltageMinNum332,\nBattBrickempMaxNum332,\nBattVoltage132,\nBrakeTempFL3FE,\nBrakeTempFR3FE,\nBrakeTempRL3FE,\nBrakeTempRR3FE,\nCMPD_inputHVCurrent,\nCMPD_inputHVPower,\nCMPD_inputHVVoltage,\nCMPD_powerLimitActive,\nCMPD_powerLimitTooLowToStart,\nCMPD_ready,\nCMPD_speedDuty,\nCMPD_speedRPM,\nCMPD_state,\nCMPD_wasteHeatState,\nCMP_HVOverVoltage,\nCMP_HVUnderVoltage,\nCMP_VCFRONTCANTimeout,\nCMP_currentSensorCal,\nCMP_failedStart,\nCMP_inverterTemperature,\nCMP_motorVoltageSat,\nCMP_overCurrent,\nCMP_overTemperature,\nCMP_ready,\nCMP_repeatOverCurrent,\nCMP_shortCircuit,\nCMP_speedDuty,\nCMP_speedRPM,\nCMP_state,\nCMP_underTemperature,\nCP_UHF_controlState,\nCP_UHF_handleFound,\nCP_acChargeCurrentLimit,\nCP_acChargeCurrentLimit_log,\nCP_acChargeState,\nCP_acNumRetries,\nCP_acPinTemperature,\nCP_apsVoltage,\nCP_boardTemperature,\nCP_cableCurrentLimit,\nCP_cableType,\nCP_chargeCablePresent,\nCP_chargeCableSecured,\nCP_chargeCableState,\nCP_chargeDoorOpen,\nCP_chargeDoorOpenUI,\nCP_chargeShutdownRequest,\nCP_chargeShutdownRequest_log,\nCP_coldWeatherMode,\nCP_coverClosed,\nCP_dTdt_dcPinActual,\nCP_dTdt_dcPinExpected,\nCP_dcPinTemperature,\nCP_dcPinTemperatureModeled,\nCP_digitalCommsAttempts,\nCP_digitalCommsEstablished,\nCP_doorButtonPressed,\nCP_doorControlState,\nCP_doorCountsDebounced,\nCP_doorCountsFiltered,\nCP_doorI,\nCP_doorLastRequestMaxI,\nCP_doorOpenRequested,\nCP_doorPot,\nCP_evseAccept,\nCP_evseChargeType,\nCP_evseChargeType_UI,\nCP_evseChargeType_log,\nCP_evseInstantDcCurrentLimit,\nCP_evseInstantDcPowerLimit,\nCP_evseMaxDcCurrentLimit,\nCP_evseMaxDcPowerLimit,\nCP_evseMaxDcVoltageLimit,\nCP_evseMinDcCurrentLimit,\nCP_evseMinDcVoltageLimit,\nCP_evseOutputDcCurrent,\nCP_evseOutputDcCurrentStale,\nCP_evseOutputDcVoltage,\nCP_evseRequest,\nCP_faultLineSensed,\nCP_gbState,\nCP_gbdcChargeAttempts,\nCP_gbdcFailureReason,\nCP_gbdcStopChargeReason,\nCP_hvChargeStatus,\nCP_hvChargeStatus_log,\nCP_hvInletExposed,\nCP_iecComboState,\nCP_inductiveDoorState,\nCP_inductiveSensorState,\nCP_insertEnableLine,\nCP_internalMaxAcCurrentLimit,\nCP_internalMaxAcCurrentLimit_log,\nCP_internalMaxDcCurrentLimit,\nCP_internalMaxDcCurrentLimit_log,\nCP_latch2ControlState,\nCP_latch2I,\nCP_latch2State,\nCP_latchControlState,\nCP_latchEngaged,\nCP_latchI,\nCP_latchState,\nCP_ledColor,\nCP_numAlertsSet,\nCP_permanentPowerRequest,\nCP_pilot,\nCP_pilotCurrent,\nCP_pinTemperature1,\nCP_pinTemperature2,\nCP_pinTemperature3,\nCP_proximity,\nCP_swcanRelayClosed,\nCP_teslaDcState,\nCP_teslaSwcanState,\nCP_type,\nCP_vehicleIsoCheckRequired,\nCP_vehicleIsoCheckRequired_log,\nCP_vehiclePrechargeRequired,\nCP_vehiclePrechargeRequired_log,\nCP_vehicleUnlockRequest,\nChargeHoursRemaining132,\nChargeLineCurrent264,\nChargeLineCurrentLimit264,\nChargeLinePower264,\nChargeLineVoltage264,\nChecksum1D8,\nCounter1D8,\nDAS_ahlbOverride,\nDAS_autopilotState,\nDAS_autosteerHPPUsage,\nDAS_autosteerVehiclesUsage,\nDAS_blindSpotRearLeft,\nDAS_blindSpotRearRight,\nDAS_bodyControlsChecksum,\nDAS_bodyControlsCounter,\nDAS_dynamicBrakeLightRequest,\nDAS_forwardCollisionWarning,\nDAS_fusedSpeedLimit,\nDAS_hazardLightRequest,\nDAS_headlightRequest,\nDAS_heaterRequest,\nDAS_heaterState,\nDAS_highLowBeamDecision,\nDAS_highLowBeamOffReason,\nDAS_leadVeh2Dx,\nDAS_leadVeh2Dy,\nDAS_leadVeh2Id,\nDAS_leadVeh2RelevantForControl,\nDAS_leadVeh2Type,\nDAS_leadVeh2VxRel,\nDAS_leadVehDx,\nDAS_leadVehDy,\nDAS_leadVehId,\nDAS_leadVehRelevantForControl,\nDAS_leadVehType,\nDAS_leadVehVxRel,\nDAS_mirrorFoldRequest,\nDAS_radarHeaterRequest,\nDAS_summonClearedGate,\nDAS_summonObstacle,\nDAS_suppressSpeedWarning,\nDAS_turnIndicatorRequest,\nDAS_turnIndicatorRequestReason,\nDAS_visionOnlySpeedLimit,\nDAS_wiperSpeed,\nDCDC12VSupportRtyCnt224,\nDCDC12VSupportStatus224,\nDCDCDischargeRtyCnt224,\nDCDCFaulted224,\nDCDCHvBusDischargeStatus224,\nDCDCInitialPrechargeSubState224,\nDCDCOutputIsLimited224,\nDCDCPrechargeRestartCnt224,\nDCDCPrechargeRtyCnt224,\nDCDCPrechargeStatus224,\nDCDCPwmEnableLine224,\nDCDCSubState224,\nDCDCSupportingFixedLvTarget224,\nDCDCoutputCurrent224,\nDCDCoutputCurrentMax224,\nDCDCstate224,\nDIF_FPGA_version,\nDIF_appGitHash,\nDIF_applicationCrc,\nDIF_assemblyId,\nDIF_axleSpeed,\nDIF_axleSpeedQF,\nDIF_bootGitHash,\nDIF_bootloaderCrc,\nDIF_buildConfigurationId,\nDIF_buildType,\nDIF_componentId,\nDIF_dcCableCurrentEst,\nDIF_dcLinkCapTemp,\nDIF_gateDriveState,\nDIF_gateDriveSupplyState,\nDIF_hardwareId,\nDIF_hvDcCableTemp,\nDIF_infoBootLdUdsProtocolVersion,\nDIF_inverterTQF,\nDIF_negDcBusbarTemp,\nDIF_oilPumpAppCrc,\nDIF_oilPumpBuildType,\nDIF_pcbaId,\nDIF_phaseOutBusbarTemp,\nDIF_phaseOutBusbarWeldTemp,\nDIF_phaseOutLugTemp,\nDIF_platformTyp,\nDIF_posDcBusbarTemp,\nDIF_powerStageSafeState,\nDIF_rotorMaxMagnetTemp,\nDIF_slavePedalPos,\nDIF_statorEndWindingTemp,\nDIF_subUsageId,\nDIF_subcomponentGitHash,\nDIF_switchingFrequency,\nDIF_sysHeatPowerOptimal,\nDIF_targetFluxMode,\nDIF_torqueActual,\nDIF_torqueChecksum,\nDIF_torqueCommand,\nDIF_torqueCounter,\nDIF_usageId,\nDIF_vBatQF,\nDIR_FPGA_version,\nDIR_appGitHash,\nDIR_applicationCrc,\nDIR_assemblyId,\nDIR_axleSpeed,\nDIR_axleSpeedQF,\nDIR_bootGitHash,\nDIR_bootloaderCrc,\nDIR_buildConfigurationId,\nDIR_buildType,\nDIR_componentId,\nDIR_controlStack,\nDIR_dcCableCurrentEst,\nDIR_dcLinkCapTemp,\nDIR_decodeHardwareStack,\nDIR_eepromStack,\nDIR_gateDriveState,\nDIR_gateDriveSupplyState,\nDIR_hardwareId,\nDIR_hvDcCableTemp,\nDIR_idleStack,\nDIR_immobilizerStack,\nDIR_infoBootLdUdsProtocolVersion,\nDIR_inverterTQF,\nDIR_module10HzStack,\nDIR_negDcBusbarTemp,\nDIR_oilPumpAppCrc,\nDIR_oilPumpBuildType,\nDIR_oilPumpFlowActual,\nDIR_oilPumpFlowTarget,\nDIR_oilPumpFluidT,\nDIR_oilPumpFluidTQF,\nDIR_oilPumpLeadAngle,\nDIR_oilPumpPhaseCurrent,\nDIR_oilPumpPressureEstimate,\nDIR_oilPumpPressureExpected,\nDIR_oilPumpPressureResidual,\nDIR_oilPumpState,\nDIR_pcbaId,\nDIR_phaseOutBusbarTemp,\nDIR_phaseOutBusbarWeldTemp,\nDIR_phaseOutLugTemp,\nDIR_platformTyp,\nDIR_posDcBusbarTemp,\nDIR_powerStageSafeState,\nDIR_rotorMaxMagnetTemp,\nDIR_rotorOffsetEst,\nDIR_rotorOffsetMean,\nDIR_slavePedalPos,\nDIR_statorEndWindingTemp,\nDIR_subUsageId,\nDIR_subcomponentGitHash,\nDIR_switchingFrequency,\nDIR_sysHeatPowerOptimal,\nDIR_systemStack,\nDIR_targetFluxMode,\nDIR_torqueActual,\nDIR_torqueChecksum,\nDIR_torqueCommand,\nDIR_torqueCounter,\nDIR_udsStack,\nDIR_usageId,\nDIR_vBatQF,\nDIR_xcpStack,\nDIS_activeInletTempReq,\nDIS_coolantFlowReq,\nDIS_oilFlowReq,\nDIS_passiveInletTempReq,\nDI_accelPedalPos,\nDI_activeInletTempReq,\nDI_brakePedalState,\nDI_btcStateUI,\nDI_coolantFlowReq,\nDI_driveBlocked,\nDI_epbRequest,\nDI_gear,\nDI_immobilizerState,\nDI_keepDrivePowerStateRequest,\nDI_limitBaseSpeed,\nDI_limitClutch,\nDI_limitDcCapTemp,\nDI_limitDeltaFluidTemp,\nDI_limitDiff,\nDI_limitDischargePower,\nDI_limitDriveTorque,\nDI_limitGracefulPowerOff,\nDI_limitIBat,\nDI_limitIGBTJunctTemp,\nDI_limitInverterTemp,\nDI_limitLimpMode,\nDI_limitMotorCurrent,\nDI_limitMotorSpeed,\nDI_limitMotorVoltage,\nDI_limitObstacleDetection,\nDI_limitOilPumpFluidTemp,\nDI_limitPCBTemp,\nDI_limitPoleTemp,\nDI_limitRegenPower,\nDI_limitRegenTorque,\nDI_limitRotorTemp,\nDI_limitShift,\nDI_limitShockTorque,\nDI_limitStatorFrequency,\nDI_limitStatorTemp,\nDI_limitTCDrive,\nDI_limitTCRegen,\nDI_limitVBatHigh,\nDI_limitVBatLow,\nDI_limitVehicleSpeed,\nDI_limitdcLinkCapTemp,\nDI_limithvDcCableTemp,\nDI_limitnegDcBusbarTemp,\nDI_limitphaseOutBusBarWeldTemp,\nDI_limitphaseOutBusbarTemp,\nDI_limitphaseOutLugTemp,\nDI_limitposDcBusbarTemp,\nDI_oilFlowReq,\nDI_passiveInletTempReq,\nDI_primaryUnitSiliconType,\nDI_proximity,\nDI_ptcStateUI,\nDI_regenLight,\nDI_speedChecksum,\nDI_speedCounter,\nDI_systemState,\nDI_systemStatusChecksum,\nDI_systemStatusCounter,\nDI_tcTelltaleFlash,\nDI_tcTelltaleOn,\nDI_trackModeState,\nDI_tractionControlMode,\nDI_tractionControlModeUI,\nDI_uiSpeed,\nDI_uiSpeedHighSpeed,\nDI_uiSpeedUnits,\nDI_vdcTelltaleFlash,\nDI_vdcTelltaleOn,\nDI_vehicleHoldTelltaleOn,\nDI_vehicleSpeed,\nElevation3D8,\nFrontExcessHeatCmd,\nFrontHeatPower2E5,\nFrontHeatPowerMax2E5,\nFrontHeatPowerOptimal2E5,\nFrontHighVoltage1A5,\nFrontMotorCurrent1A5,\nFrontOilFlowActual396,\nFrontOilPumpDutyCycle396,\nFrontOilPumpFluidTemp396,\nFrontOilPumpLeadAngle396,\nFrontOilPumpOilTempEst396,\nFrontOilPumpOilTempEstConfident3,\nFrontOilPumpPhaseCurrent396,\nFrontOilPumpPressureEstimate396,\nFrontOilPumpPressureExpected396,\nFrontOilPumpState396,\nFrontPower2E5,\nFrontPowerLimit2E5,\nFrontTorque1D5,\nFrontTorqueRequest1D5,\nGPSAccuracy04F,\nGPSLatitude04F,\nGPSLongitude04F,\nGTW_activeHighBeam,\nGTW_airSuspension,\nGTW_airbagCutoffSwitch,\nGTW_audioType,\nGTW_autopilot,\nGTW_autopilotCameraType,\nGTW_auxParkLamps,\nGTW_bPillarNFCParam,\nGTW_birthday,\nGTW_bmpState,\nGTW_brakeHWType,\nGTW_brakeLineSwitchType,\nGTW_cabinPTCHeaterType,\nGTW_chassisType,\nGTW_compressorType,\nGTW_connectivityPackage,\nGTW_coolantPumpType,\nGTW_country,\nGTW_dasHw,\nGTW_deliveryStatus,\nGTW_drivetrainType,\nGTW_eBuckConfig,\nGTW_eCallEnabled,\nGTW_efficiencyPackage,\nGTW_epasType,\nGTW_espValveType,\nGTW_exteriorColor,\nGTW_frontFogLamps,\nGTW_frontSeatHeaters,\nGTW_frontSeatReclinerHardware,\nGTW_frontSeatType,\nGTW_headlamps,\nGTW_headlightLevelerType,\nGTW_homelinkType,\nGTW_hvacPanelVaneType,\nGTW_immersiveAudio,\nGTW_interiorLighting,\nGTW_intrusionSensorType,\nGTW_lumbarECUType,\nGTW_mapRegion,\nGTW_memoryMirrors,\nGTW_numberHVILNodes,\nGTW_packEnergy,\nGTW_passengerAirbagType,\nGTW_passengerOccupancySensorType,\nGTW_pedestrianWarningSound,\nGTW_performancePackage,\nGTW_plcSupportType,\nGTW_powerSteeringColumn,\nGTW_radarHeaterType,\nGTW_rearFogLamps,\nGTW_rearGlassType,\nGTW_rearLightType,\nGTW_rearSeatHeaters,\nGTW_refrigerantType,\nGTW_restraintsHardwareType,\nGTW_rightHandDrive,\nGTW_roofGlassType,\nGTW_roofType,\nGTW_softRange,\nGTW_spoilerType,\nGTW_steeringColumnMotorType,\nGTW_steeringColumnUJointType,\nGTW_superchargingAccess,\nGTW_tireType,\nGTW_towPackage,\nGTW_tpmsType,\nGTW_twelveVBatteryType,\nGTW_vdcType,\nGTW_wheelType,\nGTW_windshieldType,\nGTW_xcpESP,\nGTW_xcpIbst,\nGearLeverButton229,\nGearLeverPosition229,\nHVP_dcLinkAllowedToEnergize,\nHVP_dcLinkVoltageFiltered,\nHVP_dcLinkVoltageRequest,\nHVP_fcContNegativeAuxOpen,\nHVP_fcContNegativeState,\nHVP_fcContPositiveAuxOpen,\nHVP_fcContPositiveState,\nHVP_fcContactorSetState,\nHVP_fcCtrsClosingAllowed,\nHVP_fcCtrsOpenNowRequested,\nHVP_fcCtrsOpenRequested,\nHVP_fcCtrsRequestStatus,\nHVP_fcCtrsResetRequestRequired,\nHVP_fcLinkAllowedToEnergize,\nHVP_hvilStatus,\nHVP_packContNegativeState,\nHVP_packContPositiveState,\nHVP_packContactorSetState,\nHVP_packCtrsClosingAllowed,\nHVP_packCtrsOpenNowRequested,\nHVP_packCtrsOpenRequested,\nHVP_packCtrsRequestStatus,\nHVP_packCtrsResetRequestRequired,\nHVP_pcsChargeHwEnabled,\nHVP_pcsControlRequest,\nHVP_pcsDcdcHwEnabled,\nHVP_pyroTestInProgress,\nIBST_driverBrakeApply,\nIBST_iBoosterStatus,\nIBST_internalState,\nIBST_sInputRodDriver,\nIBST_statusChecksum,\nIBST_statusCounter,\nMaxChargeCurrent2D2,\nMaxDischargeCurrent2D2,\nMaxVoltage2D2,\nMinVoltage2D2,\nOdometer3B6,\nPCS_chargeShutdownRequest,\nPCS_chgInstantAcPowerAvailable,\nPCS_chgMainState,\nPCS_chgMaxAcPowerAvailable,\nPCS_chgPHAEnable,\nPCS_chgPHALineCurrentRequest,\nPCS_chgPHBEnable,\nPCS_chgPHBLineCurrentRequest,\nPCS_chgPHCEnable,\nPCS_chgPHCLineCurrentRequest,\nPCS_chgPwmEnableLine,\nPCS_dcdcHvBusVolt,\nPCS_dcdcLvBusVolt,\nPCS_dcdcLvOutputCurrent,\nPCS_ecuLogUploadRequest224,\nPCS_gridConfig,\nPCS_hvChargeStatus,\nPCS_hwVariantType,\nPTC_leftCurrentHV,\nPTC_leftTempIGBT,\nPTC_rightCurrentHV,\nPTC_rightTempIGBT,\nPTC_tempOCP,\nPTC_tempPCB,\nPTC_voltageHV,\nRawBattCurrent132,\nRearExcessHeatCmd,\nRearHeatPower266,\nRearHeatPowerMax266,\nRearHeatPowerOptimal266,\nRearHighVoltage126,\nRearMotorCurrent126,\nRearPower266,\nRearPowerLimit266,\nRearTempInvCapbank315,\nRearTempInvHeatsink315,\nRearTempInvPCB315,\nRearTempInverter315,\nRearTempPctInverter315,\nRearTempPctStator315,\nRearTempStator315,\nRearTorque1D8,\nRearTorqueRequest1D8,\nSCCM_highBeamStalkStatus,\nSCCM_leftStalkCounter,\nSCCM_leftStalkCrc,\nSCCM_leftStalkReserved1,\nSCCM_turnIndicatorStalkStatus,\nSCCM_washWipeButtonStatus,\nSOCUI292,\nSOCave292,\nSOCmax292,\nSOCmin292,\nSmoothBattCurrent132,\nStatusFlags,\nSteeringAngle129,\nSteeringSensorA129,\nSteeringSensorB129,\nSteeringSensorC129,\nSteeringSpeed129,\nSystemDrivePowerMax268,\nSystemHeatPower268,\nSystemHeatPowerMax268,\nSystemRegenPowerMax268,\nTPMSFLpressure31F,\nTPMSFLtemp31F,\nTPMSFRpressure31F,\nTPMSFRtemp31F,\nTPMSRLpressure31F,\nTPMSRLtemp31F,\nTPMSRRpressure31F,\nTPMSRRtemp31F,\nTempInvCapbank376,\nTempInvHeatsink376,\nTempInvPCB376,\nTempInverter376,\nTempPctInverter376,\nTempPctStator376,\nTempStator376,\nTorqueFlags1D8,\nTotalChargeKWh3D2,\nTotalDischargeKWh3D2,\nUI_DIAppSliderDebug,\nUI_PINToDriveEnabled,\nUI_PINToDrivePassed,\nUI_Range,\nUI_SOC,\nUI_UMCUpdateInhibit,\nUI_VCLEFTFeature1,\nUI_VCSECFeature1,\nUI_WCUpdateInhibit,\nUI_a001_DriverDoorOpen,\nUI_a002_DoorOpen,\nUI_a003_TrunkOpen,\nUI_a004_FrunkOpen,\nUI_a005_HeadlightsOnDoorOpen,\nUI_a006_RemoteServiceAlert,\nUI_a007_SoftPackConfigMismatch,\nUI_a008_TouchScreenError,\nUI_a009_SquashfsError,\nUI_a010_MapsMissing,\nUI_a011_IncorrectMap,\nUI_a012_NotOnPrivateProperty,\nUI_a013_TPMSHardWarning,\nUI_a014_TPMSSoftWarning,\nUI_a015_TPMSOverPressureWarning,\nUI_a016_TPMSTemperatureWarning,\nUI_a017_TPMSSystemFault,\nUI_a018_SlipStartOn,\nUI_a019_ParkBrakeFault,\nUI_a020_SteeringReduced,\nUI_a021_RearSeatbeltUnbuckled,\nUI_a022_ApeFusesEtc,\nUI_a023_CellInternetCheckFailed,\nUI_a024_WifiInternetCheckFailed,\nUI_a025_WifiOnlineCheckFailed,\nUI_a026_ModemResetLoopDetected,\nUI_a027_AutoSteerMIA,\nUI_a028_FrontTrunkPopupClosed,\nUI_a029_ModemMIA,\nUI_a030_ModemVMCrash,\nUI_a031_BrakeFluidLow,\nUI_a032_CellModemRecoveryResets,\nUI_a033_ApTrialExpired,\nUI_a034_WakeupProblem,\nUI_a035_AudioWatchdogKernelError,\nUI_a036_AudioWatchdogHfpError,\nUI_a037_AudioWatchdogXrunStormEr,\nUI_a038_AudioWatchdogA2bI2cLocku,\nUI_a039_AudioA2bNeedRediscovery,\nUI_a040_HomelinkTransmit,\nUI_a041_AudioDmesgXrun,\nUI_a042_AudioDmesgRtThrottling,\nUI_a043_InvalidMapDataOverride,\nUI_a044_AudioDmesgDspException,\nUI_a045_ECallNeedsService,\nUI_a046_BackupCameraStreamError,\nUI_a047_CellRoamingDisallowed,\nUI_a048_AudioPremiumAmpCheckFail,\nUI_a049_BrakeShiftRequired,\nUI_a050_BackupCameraIPUTimeout,\nUI_a051_BackupCameraFrameTimeout,\nUI_a052_KernelPanicReported,\nUI_a053_QtCarExitError,\nUI_a054_AudioBoostPowerBad,\nUI_a055_ManualECallDisabled,\nUI_a056_ManualECallButtonDisconn,\nUI_a057_CellAntennaDisconnected,\nUI_a058_GPSAntennaDisconnected,\nUI_a059_ECallSpeakerDisconnected,\nUI_a060_ECallMicDisconnected,\nUI_a061_SIMTestFailed,\nUI_a062_ENSTestFailed,\nUI_a063_CellularTestFailed,\nUI_a064_ModemFirmwareTestFailed,\nUI_acChargeCurrentLimit,\nUI_accOvertakeEnable,\nUI_accessoryPowerRequest,\nUI_aebEnable,\nUI_aesEnable,\nUI_ahlbEnable,\nUI_alarmEnabled,\nUI_alarmTriggerRequest,\nUI_ambientLightingEnabled,\nUI_audioActive,\nUI_autoFoldMirrorsOn,\nUI_autoHighBeamEnabled,\nUI_autoLaneChangeEnable,\nUI_autoParkRequest,\nUI_autoRollWindowsOnLockEnable,\nUI_autopilotPowerStateRequest,\nUI_autopilotTrial,\nUI_batteryPreconditioningRequest,\nUI_bluetoothActive,\nUI_brickBalancingDisabled,\nUI_brickVLoggingRequest,\nUI_bsdEnable,\nUI_cameraActive,\nUI_cellActive,\nUI_cellConnected,\nUI_cellNetworkTechnology,\nUI_cellReceiverPower,\nUI_cellSignalBars,\nUI_chargeEnableRequest,\nUI_chargeTerminationPct,\nUI_chassisControlChecksum,\nUI_chassisControlCounter,\nUI_childDoorLockOn,\nUI_closeChargePortDoorRequest,\nUI_closureConfirmed,\nUI_coastDownMode,\nUI_conditionalLimitActive,\nUI_conditionalLoggingEnabledVCSE,\nUI_conditionalSpeedLimit,\nUI_cpInletHeaterRequest,\nUI_cpuTemperature,\nUI_dasDebugEnable,\nUI_developmentCar,\nUI_displayBrightnessLevel,\nUI_displayOn,\nUI_displayReady,\nUI_distanceUnits,\nUI_domeLightSwitch,\nUI_driveStateRequest,\nUI_efuseMXResistanceEstArmed,\nUI_energyAtDestination,\nUI_factoryReset,\nUI_falseTouchCounter,\nUI_fcwEnable,\nUI_fcwSensitivity,\nUI_freeRollModeRequest,\nUI_frontFogSwitch,\nUI_frontLeftSeatHeatReq,\nUI_frontRightSeatHeatReq,\nUI_frunkRequest,\nUI_globalUnlockOn,\nUI_gloveboxRequest,\nUI_gpsActive,\nUI_gpsAntennaDisconnected,\nUI_gpsHDOP,\nUI_gpsNmeaMIA,\nUI_gpsVehicleHeading,\nUI_gpsVehicleSpeed,\nUI_hindsightEnergy,\nUI_honkHorn,\nUI_hvacReqACDisable,\nUI_hvacReqAirDistributionMode,\nUI_hvacReqBlowerSegment,\nUI_hvacReqKeepClimateOn,\nUI_hvacReqManualDefogState,\nUI_hvacReqRecirc,\nUI_hvacReqSecondRowState,\nUI_hvacReqTempSetpointLeft,\nUI_hvacReqTempSetpointRight,\nUI_hvacReqUserPowerState,\nUI_hvacUseModeledDuctTemp,\nUI_idealRange,\nUI_intrusionSensorOn,\nUI_isSunUp,\nUI_latControlEnable,\nUI_ldwEnable,\nUI_lightSwitch,\nUI_limitMode,\nUI_lockRequest,\nUI_locksPanelActive,\nUI_mapSpeedLimitUnits,\nUI_minsToSunrise,\nUI_minsToSunset,\nUI_mirrorDipOnReverse,\nUI_mirrorFoldRequest,\nUI_mirrorHeatRequest,\nUI_motorOnMode,\nUI_mppSpeedLimit,\nUI_narrowGarages,\nUI_navToSupercharger,\nUI_openChargePortDoorRequest,\nUI_parkBrakeRequest,\nUI_pcbTemperature,\nUI_pedalMap,\nUI_pedalSafetyEnable,\nUI_powerExpected,\nUI_powerIdeal,\nUI_powerOff,\nUI_powertrainControlChecksum,\nUI_powertrainControlCounter,\nUI_predictedEnergy,\nUI_radioActive,\nUI_ratedWHpM,\nUI_readyForDrive,\nUI_readyToAddKey,\nUI_rearCenterSeatHeatReq,\nUI_rearFogSwitch,\nUI_rearLeftSeatHeatReq,\nUI_rearRightSeatHeatReq,\nUI_rearWindowLockout,\nUI_rebootAutopilot,\nUI_redLightStopSignEnable,\nUI_regenTorqueMax,\nUI_remoteClosureRequest,\nUI_remoteStartRequest,\nUI_requestActiveBatteryHeating,\nUI_scheduledDepartureEnabled,\nUI_screenPCBTemperature,\nUI_screenshotActive,\nUI_seeYouHomeLightingOn,\nUI_selfParkTune,\nUI_shorted12VCellTestMode,\nUI_smartAcChargingEnabled,\nUI_socSnapshotExpirationTime,\nUI_solarAzimuthAngle,\nUI_solarAzimuthAngleCarRef,\nUI_solarElevationAngle,\nUI_soundHornOnLock,\nUI_speedLimit,\nUI_steeringBacklightEnabled,\nUI_steeringButtonMode,\nUI_steeringTuneRequest,\nUI_stop12vSupport,\nUI_stoppingMode,\nUI_summonActive,\nUI_summonState,\nUI_systemActive,\nUI_systemPowerLimit,\nUI_systemTorqueLimit,\nUI_touchActive,\nUI_trackCmpOverclock,\nUI_trackModeRequest,\nUI_trackModeSettingsChecksum,\nUI_trackModeSettingsCounter,\nUI_trackPostCooling,\nUI_trackRotationTendency,\nUI_trackStabilityAssist,\nUI_tractionControlMode,\nUI_trailerMode,\nUI_tripPlanningActive,\nUI_trunkRequest,\nUI_uSOE,\nUI_unlockOnPark,\nUI_userPresent,\nUI_userSpeedOffset,\nUI_userSpeedOffsetUnits,\nUI_vpnActive,\nUI_walkAwayLock,\nUI_walkUpUnlock,\nUI_wasteMode,\nUI_wasteModeRegenLimit,\nUI_wifiActive,\nUI_wifiConnected,\nUI_winchModeRequest,\nUI_windowRequest,\nUI_wiperMode,\nUI_wiperRequest,\nUI_zeroSpeedConfirmed,\nUIcarWashModeRequest284,\nUIfactoryMode284,\nUIgameMode284,\nUIhomelinkV2Command0284,\nUIhomelinkV2Command1284,\nUIhomelinkV2Command2284,\nUIisDelivered284,\nUIsentryMode284,\nUIserviceMode284,\nUIshowroomMode284,\nUItransportMode284,\nUIvaletMode284,\nUTCday318,\nUTChour318,\nUTCminutes318,\nUTCmonth318,\nUTCseconds318,\nUTCyear318,\nUnixTimeSeconds528,\nVCFRONT_12VARailStable,\nVCFRONT_12VBRailStable,\nVCFRONT_12VBatteryStatusChecksum,\nVCFRONT_12VBatteryStatusCounter,\nVCFRONT_12VBatteryTargetVoltage,\nVCFRONT_12VOverchargeCounter,\nVCFRONT_12vStatusForDrive,\nVCFRONT_2RowCenterUnbuckled,\nVCFRONT_2RowLeftUnbuckled,\nVCFRONT_2RowRightUnbuckled,\nVCFRONT_5VARailStable,\nVCFRONT_5VBRailStable,\nVCFRONT_APGlassHeaterState,\nVCFRONT_AS8510Voltage,\nVCFRONT_CCQdotActual,\nVCFRONT_CCQdotFdFrwrdTarget,\nVCFRONT_CCQdotFdbk,\nVCFRONT_CMPDLVState,\nVCFRONT_CMPDischargeSuperheat,\nVCFRONT_CMPEnable,\nVCFRONT_CMPPowerLimit,\nVCFRONT_CMPReset,\nVCFRONT_CMPTargetDuty,\nVCFRONT_ChargePumpVoltage,\nVCFRONT_ChargePumpVoltageStable,\nVCFRONT_DIQdotA,\nVCFRONT_DRLLeftStatus,\nVCFRONT_DRLRightStatus,\nVCFRONT_EPAS3PCurrent,\nVCFRONT_EPAS3PFault,\nVCFRONT_EPAS3PSelfTestResult,\nVCFRONT_EPAS3PState,\nVCFRONT_EPAS3PTemp,\nVCFRONT_EPAS3PVoltage,\nVCFRONT_EPAS3SCurrent,\nVCFRONT_EPAS3SFault,\nVCFRONT_EPAS3SSelfTestResult,\nVCFRONT_EPAS3SState,\nVCFRONT_EPAS3STemp,\nVCFRONT_EPAS3SVoltage,\nVCFRONT_ESPMotorCurrent,\nVCFRONT_ESPMotorFault,\nVCFRONT_ESPMotorSelfTestResult,\nVCFRONT_ESPMotorState,\nVCFRONT_ESPMotorTemp,\nVCFRONT_ESPMotorVoltage,\nVCFRONT_ESPValveCurrent,\nVCFRONT_ESPValveFault,\nVCFRONT_ESPValveState,\nVCFRONT_ESPValveTemp,\nVCFRONT_ESPValveVoltage,\nVCFRONT_HCML_bladeTemp,\nVCFRONT_HCML_diffuseTemp,\nVCFRONT_HCML_highBeamTemp,\nVCFRONT_HCML_lowBeamSpotTemp,\nVCFRONT_HCML_turnTemp,\nVCFRONT_HCMR_bladeTemp,\nVCFRONT_HCMR_diffuseTemp,\nVCFRONT_HCMR_highBeamTemp,\nVCFRONT_HCMR_lowBeamSpotTemp,\nVCFRONT_HCMR_turnTemp,\nVCFRONT_HSDInitCompleteU13,\nVCFRONT_HSDInitCompleteU16,\nVCFRONT_IBSCurrent,\nVCFRONT_IBSFault,\nVCFRONT_IBSUnfilteredTemperature,\nVCFRONT_LVBatteryDisconnected,\nVCFRONT_LVBatterySupported,\nVCFRONT_LVLoadRequest,\nVCFRONT_PCSCurrent,\nVCFRONT_PCSFault,\nVCFRONT_PCSMia,\nVCFRONT_PCSState,\nVCFRONT_PCSTemp,\nVCFRONT_PCSVoltage,\nVCFRONT_PDischargeControllerOutp,\nVCFRONT_PEResetLineState,\nVCFRONT_PSuctionControllerOutput,\nVCFRONT_accPlusAvailable,\nVCFRONT_activeLouverOpenPos,\nVCFRONT_activeLouverOpenPosTarg,\nVCFRONT_airCompressorStatus,\nVCFRONT_ambientColderThanBatt,\nVCFRONT_ambientLightingBrightnes,\nVCFRONT_ambientSourcingAvailable,\nVCFRONT_ambientSourcingDisabled,\nVCFRONT_amplifierLVRequest,\nVCFRONT_anyClosureOpen,\nVCFRONT_anyDoorOpen,\nVCFRONT_approachLightingRequest,\nVCFRONT_autopilot1Current,\nVCFRONT_autopilot1Fault,\nVCFRONT_autopilot1State,\nVCFRONT_autopilot1Temp,\nVCFRONT_autopilot1Voltage,\nVCFRONT_autopilot2Current,\nVCFRONT_autopilot2Fault,\nVCFRONT_autopilot2State,\nVCFRONT_autopilot2Temp,\nVCFRONT_autopilot2Voltage,\nVCFRONT_battDissipation,\nVCFRONT_battLoopWorthCooling,\nVCFRONT_battOverStagUpperLimit,\nVCFRONT_battSensorIrrational,\nVCFRONT_battUnderStagUpperLimit,\nVCFRONT_batterySMState,\nVCFRONT_batterySupportRequest,\nVCFRONT_bmsHvChargeEnable,\nVCFRONT_brakeFluidLevel,\nVCFRONT_cabinHeatEnergyDuringDri,\nVCFRONT_calibratedPositionHCML,\nVCFRONT_calibratedPositionHCMR,\nVCFRONT_ccLeftExvCalibFailed,\nVCFRONT_ccLeftExvCalibOffset,\nVCFRONT_ccLeftExvRange,\nVCFRONT_ccRightExvCalibFailed,\nVCFRONT_ccRightExvCalibOffset,\nVCFRONT_ccRightExvRange,\nVCFRONT_cclExvFlow,\nVCFRONT_ccrExvFlow,\nVCFRONT_chargeNeeded,\nVCFRONT_chargedIBSAmpHours,\nVCFRONT_chillerDemandActive,\nVCFRONT_chillerExvCalibFailed,\nVCFRONT_chillerExvCalibOffset,\nVCFRONT_chillerExvFlow,\nVCFRONT_chillerExvRange,\nVCFRONT_chillerInletTempEstimate,\nVCFRONT_chillerLiftDisabledLowPs,\nVCFRONT_chillerPassiveCoolPower,\nVCFRONT_compDemandChiller,\nVCFRONT_compDemandEvap,\nVCFRONT_compEnergyDuringDrive,\nVCFRONT_compPerfRecoveryLimited,\nVCFRONT_compressorState,\nVCFRONT_condenserPressureLimit,\nVCFRONT_coolantAirPurgeBatState,\nVCFRONT_coolantFillRoutineStatus,\nVCFRONT_coolantFlowBatActual,\nVCFRONT_coolantFlowBatReason,\nVCFRONT_coolantFlowBatTarget,\nVCFRONT_coolantFlowPTActual,\nVCFRONT_coolantFlowPTReason,\nVCFRONT_coolantFlowPTTarget,\nVCFRONT_coolantHasBeenFilled,\nVCFRONT_coolantLevel,\nVCFRONT_coolantLevelVoltage,\nVCFRONT_coolantValveAngleDrift,\nVCFRONT_coolantValveCountRange,\nVCFRONT_coolantValveDailyAngleTr,\nVCFRONT_coolantValveMode,\nVCFRONT_coolantValveOdometer,\nVCFRONT_coolantValveRadBypass,\nVCFRONT_coolantValveRecalCount,\nVCFRONT_coolantValveRecalReason,\nVCFRONT_coolantValveWindupEstL,\nVCFRONT_coolantValveWindupEstR,\nVCFRONT_courtesyLightingRequest,\nVCFRONT_cpLVRequest,\nVCFRONT_crashDetectedType,\nVCFRONT_crashState,\nVCFRONT_crashUnlockOverrideSet,\nVCFRONT_currentPositionHCML,\nVCFRONT_currentPositionHCMR,\nVCFRONT_cycleModelConverged,\nVCFRONT_das1HighCurrentLVState,\nVCFRONT_das2HighCurrentLVState,\nVCFRONT_diDissipation,\nVCFRONT_diPowerOnState,\nVCFRONT_difLVState,\nVCFRONT_dirLVRequest,\nVCFRONT_dischargePressureLimit,\nVCFRONT_dischargePressureTarget,\nVCFRONT_dischargedIBSAmpHours,\nVCFRONT_driverBuckleStatus,\nVCFRONT_driverDoorStatus,\nVCFRONT_driverIsLeaving,\nVCFRONT_driverIsLeavingAnySpeed,\nVCFRONT_driverPresent,\nVCFRONT_driverUnbuckled,\nVCFRONT_drlMode,\nVCFRONT_eFuseLockoutVoltage,\nVCFRONT_epasLVState,\nVCFRONT_epasWakeLine,\nVCFRONT_espLVState,\nVCFRONT_estCompPower,\nVCFRONT_estCompRefrigMassflow,\nVCFRONT_estCompressorRpm,\nVCFRONT_estPressureDisch,\nVCFRONT_estPressureLiq,\nVCFRONT_estPressureSuct,\nVCFRONT_estQLift,\nVCFRONT_estTempDisch,\nVCFRONT_estTempLiq,\nVCFRONT_estTempSuct,\nVCFRONT_evapDisabledLowPsCutout,\nVCFRONT_evapExvCalibFailed,\nVCFRONT_evapExvCalibOffset,\nVCFRONT_evapExvFlow,\nVCFRONT_evapExvRange,\nVCFRONT_evapFdFrwrdTarget,\nVCFRONT_evapFdFrwrdTargetMinimum,\nVCFRONT_evapFdbk,\nVCFRONT_exteriorQuietModeAllowed,\nVCFRONT_exteriorQuietModeEnabled,\nVCFRONT_exvFlowTarget,\nVCFRONT_exvState,\nVCFRONT_fanControlFeedfwdActive,\nVCFRONT_fanControlRadCanCool,\nVCFRONT_fanControlRadiatorInletT,\nVCFRONT_fanControlRadiatorUa,\nVCFRONT_fanDemand,\nVCFRONT_fanDemandCondenser,\nVCFRONT_fanDemandRadiator,\nVCFRONT_feedBackDuctTempControll,\nVCFRONT_feedBackEvapTempControll,\nVCFRONT_feedFwdFanDemand,\nVCFRONT_feedFwdMDotCabinCondense,\nVCFRONT_feedFwdMDotEvaporator,\nVCFRONT_feedFwdPumpDemand,\nVCFRONT_feedfwdLoadCoolingDomina,\nVCFRONT_firstChargeOTA,\nVCFRONT_firstChargePOR,\nVCFRONT_fogLeftStatus,\nVCFRONT_fogRightStatus,\nVCFRONT_freezeEvapITerm,\nVCFRONT_frunkAccessPost,\nVCFRONT_frunkInteriorRelSwitch,\nVCFRONT_frunkLatchStatus,\nVCFRONT_frunkLatchType,\nVCFRONT_good12VforUpdate,\nVCFRONT_hasLowRefrigerant,\nVCFRONT_hazardLightRequest,\nVCFRONT_hazardSwitchBacklight,\nVCFRONT_hcmlAppCRC,\nVCFRONT_hcmrAppCRC,\nVCFRONT_headlampLeftCurrent,\nVCFRONT_headlampLeftFanStatus,\nVCFRONT_headlampLeftFault,\nVCFRONT_headlampLeftState,\nVCFRONT_headlampLeftTemperature,\nVCFRONT_headlampLeftVoltage,\nVCFRONT_headlampRightCurrent,\nVCFRONT_headlampRightFanStatus,\nVCFRONT_headlampRightFault,\nVCFRONT_headlampRightState,\nVCFRONT_headlampRightTemperature,\nVCFRONT_headlampRightVoltage,\nVCFRONT_headlightLeftVPosition,\nVCFRONT_headlightRightVPosition,\nVCFRONT_highBeamLeftStatus,\nVCFRONT_highBeamRightStatus,\nVCFRONT_highBeamSwitchActive,\nVCFRONT_homelinkCommStatus,\nVCFRONT_homelinkRegionCode,\nVCFRONT_homelinkV2Response0,\nVCFRONT_homelinkV2Response1,\nVCFRONT_homelinkV2Response2,\nVCFRONT_homelinkV2Response3,\nVCFRONT_homelinkV2Response4,\nVCFRONT_hornOn,\nVCFRONT_hpAmbientSource,\nVCFRONT_hpAtSteadyState,\nVCFRONT_hpBattOverTempHvacDisabl,\nVCFRONT_hpBattStagTarget,\nVCFRONT_hpBatteryCool,\nVCFRONT_hpBatteryCoolCabinConden,\nVCFRONT_hpBatteryCoolCabinReheat,\nVCFRONT_hpBatteryCoolEvaporator,\nVCFRONT_hpBatteryHeatAmbientSour,\nVCFRONT_hpBatteryHeatCOP1,\nVCFRONT_hpCOP,\nVCFRONT_hpCabinCoolEvaporator,\nVCFRONT_hpCabinCoolEvaporatorReh,\nVCFRONT_hpCabinHeatAmbientSource,\nVCFRONT_hpCabinHeatBatteryCoolRe,\nVCFRONT_hpCabinHeatBatteryHeatRe,\nVCFRONT_hpCabinHeatBlend,\nVCFRONT_hpCabinHeatCOP1,\nVCFRONT_hpCabinHeatReheatAmbient,\nVCFRONT_hpCabinHeatReheatScaveng,\nVCFRONT_hpCabinHeatScavengeOnly,\nVCFRONT_hpCompPowerIndex,\nVCFRONT_hpCompPowerIndexFiltered,\nVCFRONT_hpDiagLouverCalib,\nVCFRONT_hpForceScavenge,\nVCFRONT_hpGeneral,\nVCFRONT_hpMode,\nVCFRONT_hpPotentialLowRefrig,\nVCFRONT_hpRefrigerantPurgeState,\nVCFRONT_hpSubcoolTarget,\nVCFRONT_hvacCompLVState,\nVCFRONT_hvacModeNotAttainable,\nVCFRONT_hvacPerfTestCommand,\nVCFRONT_hvcLVRequest,\nVCFRONT_iBoosterCurrent,\nVCFRONT_iBoosterFault,\nVCFRONT_iBoosterLVState,\nVCFRONT_iBoosterSelfTestResult,\nVCFRONT_iBoosterState,\nVCFRONT_iBoosterStateDBG,\nVCFRONT_iBoosterTemp,\nVCFRONT_iBoosterVoltage,\nVCFRONT_iBoosterWakeLine,\nVCFRONT_indicatorLeftRequest,\nVCFRONT_indicatorRightRequest,\nVCFRONT_infoAppCrc,\nVCFRONT_infoAppGitHash,\nVCFRONT_infoAssemblyId,\nVCFRONT_infoBootCrc,\nVCFRONT_infoBootGitHash,\nVCFRONT_infoBootUdsProtoVersion,\nVCFRONT_infoBuildConfigId,\nVCFRONT_infoBuildType,\nVCFRONT_infoComponentId,\nVCFRONT_infoHardwareId,\nVCFRONT_infoPcbaId,\nVCFRONT_infoPlatformType,\nVCFRONT_infoSubUsageId,\nVCFRONT_infoSubcomponent3,\nVCFRONT_infoSubcomponent4,\nVCFRONT_infoSubcomponent5,\nVCFRONT_infoSubcomponent6,\nVCFRONT_infoUsageId,\nVCFRONT_isActiveHeatingBattery,\nVCFRONT_isColdStartRunning,\nVCFRONT_isEvapOperationAllowed,\nVCFRONT_isHeatPumpOilPurgeActive,\nVCFRONT_isVehicleSupported,\nVCFRONT_lccActiveCoolTarget,\nVCFRONT_lccExvCalibFailed,\nVCFRONT_lccExvCalibOffset,\nVCFRONT_lccExvFlow,\nVCFRONT_lccExvRange,\nVCFRONT_lccInletTempEstimate,\nVCFRONT_lccPassiveHeatPower,\nVCFRONT_leftControllerCurrent,\nVCFRONT_leftControllerFault,\nVCFRONT_leftControllerState,\nVCFRONT_leftControllerTemp,\nVCFRONT_leftControllerVoltage,\nVCFRONT_lowBeamLeftStatus,\nVCFRONT_lowBeamRightStatus,"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://i.piano.io/managedservices/the-brussels-times/tesla-picture.png\">"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UI_Range\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SoC (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UI_SOC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SoC (used)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UI_SOC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance (trip)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Odometer3B6\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "kWh / 100 km",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BattVoltage132\" or r[\"_field\"] == \"RawBattCurrent132\" or r[\"_field\"] == \"DI_vehicleSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"GPSLatitude04F\" or r[\"_field\"] == \"GPSLongitude04F\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)\r\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed (km/h) and Brake Pedal State",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DI_vehicleSpeed\" or r[\"_field\"] == \"DI_brakePedalState\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance (total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Odometer3B6\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed (avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "km/h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DI_vehicleSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Discharged (kWh)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BMS_kwhDriveDischargeTotal\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Regenerated (kWh)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BMS_kwhRegenChargeTotal\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "${parameters}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /\\b${parameters:regex}\\b/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures (degC)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BMSmaxPackTemperature\" or r[\"_field\"] == \"VCFRONT_tempAmbient\" or r[\"_field\"] == \"DIR_oilPumpFluidT\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tire Pressure (bar)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TPMSFLpressure31F\" or r[\"_field\"] == \"TPMSFRpressure31F\" or r[\"_field\"] == \"TPMSRLpressure31F\" or r[\"_field\"] == \"TPMSRRpressure31F\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tire Temperature (degC)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TPMSFLtemp31F\" or r[\"_field\"] == \"TPMSFRtemp31F\" or r[\"_field\"] == \"TPMSRLtemp31F\" or r[\"_field\"] == \"TPMSRRtemp31F\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Torque (NM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FrontTorque1D5\" or r[\"_field\"] == \"RearTorque1D8\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Oil Pump Pressure (kPa)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DIR_oilPumpPressureEstimate\" or r[\"_field\"] == \"DIR_oilPumpPressureExpected\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steering Angle (deg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /\\b${devices:regex}\\b/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SteeringAngle129\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}